"""add_sentence_review_log_and_columns

Revision ID: 793efd150638
Revises: fc0b2a459238
Create Date: 2026-02-08 13:02:00.713401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793efd150638'
down_revision: Union[str, Sequence[str], None] = 'fc0b2a459238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_review_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('comprehension', sa.String(length=20), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('review_mode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lemmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grammar_features_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentence_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_type', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_review_log_sentence_id', 'sentences', ['sentence_id'], ['id'])

    with op.batch_alter_table('sentence_words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grammar_role_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_shown_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_column('last_shown_at')

    with op.batch_alter_table('sentence_words', schema=None) as batch_op:
        batch_op.drop_column('grammar_role_json')

    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_log_sentence_id', type_='foreignkey')
        batch_op.drop_column('credit_type')
        batch_op.drop_column('sentence_id')

    with op.batch_alter_table('lemmas', schema=None) as batch_op:
        batch_op.drop_column('grammar_features_json')

    op.drop_table('sentence_review_log')
    # ### end Alembic commands ###
