"""initial schema

Revision ID: affea1c30b95
Revises: 
Create Date: 2026-02-08 16:26:09.274452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affea1c30b95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_features',
    sa.Column('feature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('feature_key', sa.String(length=50), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('label_ar', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('feature_key')
    )
    op.create_table('roots',
    sa.Column('root_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('root', sa.Text(), nullable=False),
    sa.Column('core_meaning_en', sa.Text(), nullable=True),
    sa.Column('productivity_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('root_id'),
    sa.UniqueConstraint('root')
    )
    op.create_table('lemmas',
    sa.Column('lemma_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lemma_ar', sa.Text(), nullable=False),
    sa.Column('lemma_ar_bare', sa.Text(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('pos', sa.String(length=20), nullable=True),
    sa.Column('gloss_en', sa.Text(), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('transliteration_ala_lc', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('grammar_features_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['root_id'], ['roots.root_id'], ),
    sa.PrimaryKeyConstraint('lemma_id')
    )
    op.create_table('user_grammar_exposure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('comfort_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['grammar_features.feature_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arabic_text', sa.Text(), nullable=False),
    sa.Column('arabic_diacritized', sa.Text(), nullable=True),
    sa.Column('english_translation', sa.Text(), nullable=True),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('target_lemma_id', sa.Integer(), nullable=True),
    sa.Column('times_shown', sa.Integer(), nullable=True),
    sa.Column('max_word_count', sa.Integer(), nullable=True),
    sa.Column('last_shown_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_lemma_id'], ['lemmas.lemma_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_lemma_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lemma_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_state', sa.String(length=20), nullable=True),
    sa.Column('fsrs_card_json', sa.JSON(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('introduced_at', sa.DateTime(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('total_encounters', sa.Integer(), nullable=True),
    sa.Column('distinct_contexts', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lemma_id'], ['lemmas.lemma_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lemma_id')
    )
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lemma_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('fsrs_log_json', sa.JSON(), nullable=True),
    sa.Column('review_mode', sa.String(length=20), nullable=True),
    sa.Column('comprehension_signal', sa.String(length=20), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('credit_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lemma_id'], ['lemmas.lemma_id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_grammar_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['grammar_features.feature_id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_review_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('comprehension', sa.String(length=20), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('review_mode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('surface_form', sa.Text(), nullable=False),
    sa.Column('lemma_id', sa.Integer(), nullable=True),
    sa.Column('is_target_word', sa.Integer(), nullable=True),
    sa.Column('grammar_role_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lemma_id'], ['lemmas.lemma_id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_words')
    op.drop_table('sentence_review_log')
    op.drop_table('sentence_grammar_features')
    op.drop_table('review_log')
    op.drop_table('user_lemma_knowledge')
    op.drop_table('sentences')
    op.drop_table('user_grammar_exposure')
    op.drop_table('lemmas')
    op.drop_table('roots')
    op.drop_table('grammar_features')
    # ### end Alembic commands ###
