"""add word introduction fields

Revision ID: f94016ab4c1f
Revises: b4ee6c700f99
Create Date: 2026-02-08 11:42:56.400461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94016ab4c1f'
down_revision: Union[str, Sequence[str], None] = 'b4ee6c700f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productivity_score', sa.Integer(), nullable=True))

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_shown', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_word_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_lemma_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('introduced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_encounters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distinct_contexts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lemma_knowledge', schema=None) as batch_op:
        batch_op.drop_column('distinct_contexts')
        batch_op.drop_column('total_encounters')
        batch_op.drop_column('introduced_at')

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_column('max_word_count')
        batch_op.drop_column('times_shown')

    with op.batch_alter_table('roots', schema=None) as batch_op:
        batch_op.drop_column('productivity_score')

    # ### end Alembic commands ###
