"""add grammar feature tracking

Revision ID: fc0b2a459238
Revises: fe4bd59703ae
Create Date: 2026-02-08 13:00:01.860008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0b2a459238'
down_revision: Union[str, Sequence[str], None] = 'fe4bd59703ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_features',
    sa.Column('feature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('feature_key', sa.String(length=50), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('label_ar', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('feature_id'),
    sa.UniqueConstraint('feature_key')
    )
    op.create_table('user_grammar_exposure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('comfort_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['grammar_features.feature_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id')
    )
    op.create_table('sentence_grammar_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['grammar_features.feature_id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lemmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grammar_features_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('sentence_words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grammar_role_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence_words', schema=None) as batch_op:
        batch_op.drop_column('grammar_role_json')

    with op.batch_alter_table('lemmas', schema=None) as batch_op:
        batch_op.drop_column('grammar_features_json')

    op.drop_table('sentence_grammar_features')
    op.drop_table('user_grammar_exposure')
    op.drop_table('grammar_features')
    # ### end Alembic commands ###
