"""add review_mode and comprehension_signal to review_log

Revision ID: fe4bd59703ae
Revises: f94016ab4c1f
Create Date: 2026-02-08 11:53:39.502696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4bd59703ae'
down_revision: Union[str, Sequence[str], None] = 'f94016ab4c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('comprehension_signal', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_column('comprehension_signal')
        batch_op.drop_column('review_mode')

    # ### end Alembic commands ###
