from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import Language, Story, Page
from app.schemas import (
    PasteImportRequest, PdfImportRequest, StorySummary,
    PageView, TokenView, MarkWordRequest, PageTranslation,
)
from app.services import reading_intake

router = APIRouter(prefix="/api/texts", tags=["texts"])


@router.get("", response_model=list[StorySummary])
def list_stories(language_code: str | None = None, db: Session = Depends(get_db)):
    # Scope the library to one language so the reader doesn't mix Greek and
    # Latin texts. Omitting the param returns all (back-compat).
    q = db.query(Story)
    if language_code:
        q = q.filter(Story.language_code == language_code)
    stories = q.order_by(Story.created_at.desc()).all()
    out = []
    for s in stories:
        processed = (
            db.query(func.count(Page.id))
            .filter(Page.story_id == s.id, Page.processed_at.isnot(None))
            .scalar() or 0
        )
        out.append(_story_summary(s, processed, db=db))
    return out


@router.post("/paste", response_model=StorySummary)
def import_paste(req: PasteImportRequest, db: Session = Depends(get_db)):
    _check_language(db, req.language_code)
    story = reading_intake.import_paste(
        db,
        language_code=req.language_code,
        body=req.body,
        title=req.title,
        author=req.author,
    )
    return _story_summary(story, 0, db=db)


@router.post("/pdf", response_model=StorySummary)
def import_pdf(req: PdfImportRequest, db: Session = Depends(get_db)):
    _check_language(db, req.language_code)
    try:
        story = reading_intake.import_pdf(
            db,
            language_code=req.language_code,
            pdf_path=req.pdf_path,
            title=req.title,
            author=req.author,
        )
    except FileNotFoundError:
        raise HTTPException(status_code=404, detail=f"PDF not found: {req.pdf_path}")
    return _story_summary(story, 0, db=db)


@router.get("/{story_id}", response_model=StorySummary)
def get_story(story_id: int, db: Session = Depends(get_db)):
    story = db.query(Story).filter(Story.id == story_id).first()
    if not story:
        raise HTTPException(status_code=404, detail="Story not found")
    processed = (
        db.query(func.count(Page.id))
        .filter(Page.story_id == story.id, Page.processed_at.isnot(None))
        .scalar() or 0
    )
    return _story_summary(story, processed, db=db)


@router.get("/{story_id}/pages/{page_number}", response_model=PageView)
def get_page(story_id: int, page_number: int, db: Session = Depends(get_db)):
    """Lazy: tokenizes + lemmatizes on first request.

    Stamps ``page.viewed_at`` after the (possibly slow) processing returns —
    this is the signal `warm_pages_ahead` uses to decide which pages need
    pre-warming. Cron-warmed pages don't stamp this; only actual user views do.
    """
    from datetime import datetime, timezone

    result = reading_intake.get_page_view(db, story_id, page_number)
    if result is None:
        raise HTTPException(status_code=404, detail="Page not found")
    page, tokens = result
    page.viewed_at = datetime.now(timezone.utc)
    db.commit()
    total_pages = (
        db.query(func.count(Page.id)).filter(Page.story_id == story_id).scalar() or 0
    )
    return PageView(
        story_id=story_id,
        page_number=page.page_number,
        total_pages=total_pages,
        total_words=page.total_words,
        tokens=[TokenView(**t) for t in tokens],
    )


@router.get("/{story_id}/pages/{page_number}/translation", response_model=PageTranslation)
def get_page_translation(story_id: int, page_number: int, db: Session = Depends(get_db)):
    """Lazy full-page English translation for the reader's "Show English" reveal.

    Generated by an LLM on first request and cached on ``Page.translation_en``;
    subsequent requests serve from cache. The frontend prefetches this in the
    background on page load so the reveal feels instant. The LLM call runs
    outside the SQLite write transaction (see reading_intake.ensure_page_translation).
    """
    result = reading_intake.ensure_page_translation(db, story_id, page_number)
    if result is None:
        raise HTTPException(status_code=404, detail="Page not found")
    translation_en, generated, sentences = result
    return PageTranslation(
        story_id=story_id,
        page_number=page_number,
        translation_en=translation_en,
        generated=generated,
        sentences=sentences,
    )


@router.patch("/{story_id}/mark")
def mark_word(story_id: int, req: MarkWordRequest, db: Session = Depends(get_db)):
    ulk = reading_intake.mark_lemma(db, lemma_id=req.lemma_id, state=req.state)
    # Return the (possibly newly-fetched) gloss so the frontend can display it
    # without an extra round-trip. `clear` returns no ULK (it was deleted);
    # we still return the gloss so the lookup bar can keep showing English
    # after the tap-cycle reaches its "unmark" position.
    from app.models import Lemma
    if ulk is None:
        lemma = db.get(Lemma, req.lemma_id)
        return {
            "lemma_id": req.lemma_id,
            "state": None,
            "gloss_en": lemma.gloss_en if lemma else None,
        }
    lemma = db.get(Lemma, ulk.lemma_id)
    return {
        "lemma_id": ulk.lemma_id,
        "state": ulk.knowledge_state,
        "gloss_en": lemma.gloss_en if lemma else None,
    }


class MarkRemainingRequest(BaseModel):
    # Self-contained, idempotent page-advance (offline-queue safe). The red and
    # yellow taps are *applied here*, not assumed to have arrived via per-tap
    # /mark calls — so one queued entry fully describes the page outcome and
    # replays safely on reconnect. See reading_intake.apply_page_review.
    unknown_lemma_ids: list[int] = []      # red taps — enrol into acquisition
    encountered_lemma_ids: list[int] = []  # yellow taps — light "recognize"
    client_review_id: str | None = None    # whole-page idempotency key
    session_id: str | None = None
    # Legacy pre-offline field (union of red + yellow); exclusion-only.
    tapped_lemma_ids: list[int] = []


@router.post("/{story_id}/pages/{page_number}/mark_remaining")
def mark_remaining_known(
    story_id: int,
    page_number: int,
    payload: MarkRemainingRequest | None = None,
    db: Session = Depends(get_db),
):
    """Advancing a page = a green comprehension review over every content word
    the user didn't tap (the page-scale analogue of a sentence submit): untapped
    new words are presumed known, untapped words already mid-learning get a
    positive review, and the red/yellow taps are applied. Self-contained and
    idempotent on ``client_review_id`` so the offline queue can replay it.
    Returns per-bucket counts plus ``duplicate``."""
    p = payload or MarkRemainingRequest()
    result = reading_intake.apply_page_review(
        db, story_id, page_number,
        tapped_lemma_ids=p.tapped_lemma_ids,
        unknown_lemma_ids=p.unknown_lemma_ids,
        encountered_lemma_ids=p.encountered_lemma_ids,
        client_review_id=p.client_review_id,
        session_id=p.session_id,
    )
    return {"page_number": page_number, **result}


@router.post("/{story_id}/extract-sentences")
def extract_sentences(story_id: int, force: bool = False, db: Session = Depends(get_db)):
    """Harvest reviewable Sentence rows from every verified page in a story.

    Normally runs implicitly as part of page-view processing. Use this endpoint
    to backfill sentences for pages that were imported before the harvest service
    existed, or to re-harvest after a quality-gate sweep (`force=True` updates
    existing sentence ids in place and deactivates stale fragments).
    """
    if not db.query(Story).filter(Story.id == story_id).first():
        raise HTTPException(status_code=404, detail="Story not found")
    from app.services.sentence_harvest import harvest_story_sentences
    created = harvest_story_sentences(db, story_id, force=force)
    return {"story_id": story_id, "sentences_created": created}


# ─── helpers ───────────────────────────────────────────────────────────────

def _check_language(db: Session, code: str):
    if not db.query(Language).filter(Language.code == code).first():
        raise HTTPException(status_code=400, detail=f"Unknown language: {code}")


def _story_summary(s: Story, processed_pages: int, db: Session | None = None) -> StorySummary:
    first_content = (
        reading_intake.first_content_page_number(db, s.id)
        if db is not None
        else 1
    )
    return StorySummary(
        id=s.id,
        language_code=s.language_code,
        title=s.title,
        author=s.author,
        source=s.source,
        page_count=s.page_count,
        processed_pages=processed_pages,
        total_words=s.total_words or 0,
        known_count=s.known_count or 0,
        unknown_count=s.unknown_count or 0,
        status=s.status,
        created_at=s.created_at,
        first_content_page_number=first_content,
    )
