import { ReviewCard, Word, WordDetail, Stats, Analytics, LearnCandidate } from "./types";

export const MOCK_REVIEW_CARDS: ReviewCard[] = [
  {
    lemma_id: 1,
    lemma_ar: "كِتَاب",
    lemma_ar_bare: "كتاب",
    gloss_en: "book",
    root: "ك.ت.ب",
    pos: "noun",
    sentence: {
      id: 1,
      arabic: "الوَلَدُ يَقْرَأُ الكِتابَ في الغُرْفَة",
      english: "The boy reads the book in the room",
      transliteration: "al-waladu yaqraʾu al-kitāba fī al-ghurfa",
    },
  },
  {
    lemma_id: 8,
    lemma_ar: "مَدِينَة",
    lemma_ar_bare: "مدينة",
    gloss_en: "city",
    root: "م.د.ن",
    pos: "noun",
    sentence: {
      id: 2,
      arabic: "هٰذِهِ المَدينَةُ جَميلَةٌ جِدًّا",
      english: "This city is very beautiful",
      transliteration: "hādhihi al-madīnatu jamīlatun jiddan",
    },
  },
  {
    lemma_id: 20,
    lemma_ar: "مُعَلِّمَة",
    lemma_ar_bare: "معلمة",
    gloss_en: "teacher (f.)",
    root: "ع.ل.م",
    pos: "noun",
    sentence: {
      id: 3,
      arabic: "المُعَلِّمَةُ تَعْمَلُ في الجامِعَة",
      english: "The teacher works at the university",
      transliteration: "al-muʿallimatu taʿmalu fī al-jāmiʿa",
    },
  },
  {
    lemma_id: 3,
    lemma_ar: "كَتَبَ",
    lemma_ar_bare: "كتب",
    gloss_en: "he wrote",
    root: "ك.ت.ب",
    pos: "verb",
    sentence: {
      id: 4,
      arabic: "كَتَبَ الطَّالِبُ رِسالَةً طَويلَةً إِلى صَديقِهِ",
      english: "The student wrote a long letter to his friend",
      transliteration: "kataba aṭ-ṭālibu risālatan ṭawīlatan ilā ṣadīqihi",
    },
  },
  {
    lemma_id: 4,
    lemma_ar: "بَيْت",
    lemma_ar_bare: "بيت",
    gloss_en: "house",
    root: "ب.ي.ت",
    pos: "noun",
    sentence: {
      id: 5,
      arabic: "رَجَعَ الأَبُ إِلى البَيْتِ بَعْدَ العَمَل",
      english: "The father returned to the house after work",
      transliteration: "rajaʿa al-abu ilā al-bayti baʿda al-ʿamal",
    },
  },
  {
    lemma_id: 6,
    lemma_ar: "مَاء",
    lemma_ar_bare: "ماء",
    gloss_en: "water",
    root: "م.و.ه",
    pos: "noun",
    sentence: {
      id: 6,
      arabic: "الأَطْفالُ يَشْرَبونَ الماءَ البارِدَ في الصَّيْف",
      english: "The children drink cold water in the summer",
      transliteration: "al-aṭfālu yashrabūna al-māʾa al-bārida fī aṣ-ṣayf",
    },
  },
  {
    lemma_id: 7,
    lemma_ar: "قَرَأَ",
    lemma_ar_bare: "قرأ",
    gloss_en: "he read",
    root: "ق.ر.أ",
    pos: "verb",
    sentence: {
      id: 7,
      arabic: "قَرَأَتِ الطَّالِبَةُ القِصَّةَ كامِلَةً قَبْلَ النَّوْم",
      english: "The student (f.) read the story completely before sleep",
      transliteration: "qaraʾati aṭ-ṭālibatu al-qiṣṣata kāmilatan qabla an-nawm",
    },
  },
  {
    lemma_id: 9,
    lemma_ar: "طَعَام",
    lemma_ar_bare: "طعام",
    gloss_en: "food",
    root: "ط.ع.م",
    pos: "noun",
    sentence: {
      id: 8,
      arabic: "الطَّعامُ في هٰذا المَطْعَمِ لَذيذٌ وَرَخيص",
      english: "The food in this restaurant is delicious and cheap",
      transliteration: "aṭ-ṭaʿāmu fī hādhā al-maṭʿami ladhīdhun wa-rakhīṣ",
    },
  },
  {
    lemma_id: 5,
    lemma_ar: "ذَهَبَ",
    lemma_ar_bare: "ذهب",
    gloss_en: "he went",
    root: "ذ.ه.ب",
    pos: "verb",
    sentence: {
      id: 9,
      arabic: "ذَهَبَتِ الأُسْرَةُ إِلى السّوقِ صَباحًا",
      english: "The family went to the market in the morning",
      transliteration: "dhahabati al-usratu ilā as-sūqi ṣabāḥan",
    },
  },
  {
    lemma_id: 10,
    lemma_ar: "عَلِمَ",
    lemma_ar_bare: "علم",
    gloss_en: "he knew / learned",
    root: "ع.ل.م",
    pos: "verb",
    sentence: {
      id: 10,
      arabic: "عَلِمَ الطَّبيبُ أَنَّ المَريضَ يَحْتاجُ إِلى الرَّاحَة",
      english: "The doctor learned that the patient needs rest",
      transliteration: "ʿalima aṭ-ṭabību anna al-marīḍa yaḥtāju ilā ar-rāḥa",
    },
  },
  {
    lemma_id: 2,
    lemma_ar: "مَدْرَسَة",
    lemma_ar_bare: "مدرسة",
    gloss_en: "school",
    root: "د.ر.س",
    pos: "noun",
    sentence: {
      id: 11,
      arabic: "يَدْرُسُ الأَوْلادُ في المَدْرَسَةِ كُلَّ يَوْمٍ",
      english: "The boys study at the school every day",
      transliteration: "yadrusu al-awlādu fī al-madrasati kulla yawmin",
    },
  },
  {
    lemma_id: 13,
    lemma_ar: "أَكَلَ",
    lemma_ar_bare: "اكل",
    gloss_en: "he ate",
    root: "أ.ك.ل",
    pos: "verb",
    sentence: {
      id: 12,
      arabic: "أَكَلَ الوَلَدُ التُّفّاحَةَ بَعْدَ الغَداء",
      english: "The boy ate the apple after lunch",
      transliteration: "akala al-waladu at-tuffāḥata baʿda al-ghadāʾ",
    },
  },
  {
    lemma_id: 14,
    lemma_ar: "شَرِبَ",
    lemma_ar_bare: "شرب",
    gloss_en: "he drank",
    root: "ش.ر.ب",
    pos: "verb",
    sentence: null,
  },
  {
    lemma_id: 15,
    lemma_ar: "كَبِير",
    lemma_ar_bare: "كبير",
    gloss_en: "big",
    root: "ك.ب.ر",
    pos: "adjective",
    sentence: null,
  },
];

export const MOCK_WORDS: Word[] = [
  { id: 1, arabic: "كِتَاب", english: "book", transliteration: "kitāb", root: "ك.ت.ب", pos: "noun", state: "known", due_date: null },
  { id: 2, arabic: "مَدْرَسَة", english: "school", transliteration: "madrasa", root: "د.ر.س", pos: "noun", state: "learning", due_date: "2026-02-08" },
  { id: 3, arabic: "كَتَبَ", english: "he wrote", transliteration: "kataba", root: "ك.ت.ب", pos: "verb", state: "known", due_date: null },
  { id: 4, arabic: "بَيْت", english: "house", transliteration: "bayt", root: "ب.ي.ت", pos: "noun", state: "learning", due_date: "2026-02-09" },
  { id: 5, arabic: "ذَهَبَ", english: "he went", transliteration: "dhahaba", root: "ذ.ه.ب", pos: "verb", state: "new", due_date: null },
  { id: 6, arabic: "مَاء", english: "water", transliteration: "māʾ", root: "م.و.ه", pos: "noun", state: "known", due_date: null },
  { id: 7, arabic: "قَرَأَ", english: "he read", transliteration: "qaraʾa", root: "ق.ر.أ", pos: "verb", state: "learning", due_date: "2026-02-08" },
  { id: 8, arabic: "مَدِينَة", english: "city", transliteration: "madīna", root: "م.د.ن", pos: "noun", state: "new", due_date: null },
  { id: 9, arabic: "طَعَام", english: "food", transliteration: "ṭaʿām", root: "ط.ع.م", pos: "noun", state: "learning", due_date: "2026-02-10" },
  { id: 10, arabic: "عَلِمَ", english: "he knew / learned", transliteration: "ʿalima", root: "ع.ل.م", pos: "verb", state: "new", due_date: null },
  { id: 11, arabic: "وَلَد", english: "boy", transliteration: "walad", root: "و.ل.د", pos: "noun", state: "known", due_date: null },
  { id: 12, arabic: "بِنْت", english: "girl", transliteration: "bint", root: "ب.ن.ت", pos: "noun", state: "known", due_date: null },
  { id: 13, arabic: "أَكَلَ", english: "he ate", transliteration: "akala", root: "أ.ك.ل", pos: "verb", state: "learning", due_date: "2026-02-08" },
  { id: 14, arabic: "شَرِبَ", english: "he drank", transliteration: "shariba", root: "ش.ر.ب", pos: "verb", state: "new", due_date: null },
  { id: 15, arabic: "كَبِير", english: "big", transliteration: "kabīr", root: "ك.ب.ر", pos: "adjective", state: "known", due_date: null },
];

export const MOCK_WORD_DETAIL: WordDetail = {
  id: 1,
  arabic: "كِتَاب",
  english: "book",
  transliteration: "kitāb",
  root: "ك.ت.ب",
  pos: "noun",
  state: "known",
  due_date: null,
  frequency_rank: 142,
  times_reviewed: 12,
  correct_count: 10,
  root_family: [
    { id: 3, arabic: "كَتَبَ", english: "he wrote" },
    { id: 16, arabic: "مَكْتَب", english: "office / desk" },
    { id: 17, arabic: "مَكْتَبَة", english: "library / bookstore" },
    { id: 18, arabic: "كَاتِب", english: "writer" },
  ],
};

export const MOCK_STATS: Stats = {
  total_words: 302,
  known_words: 45,
  learning_words: 87,
  new_words: 170,
  due_today: 10,
  reviews_today: 0,
  streak_days: 3,
};

export const MOCK_LEARN_CANDIDATES: LearnCandidate[] = [
  {
    lemma_id: 50,
    lemma_ar: "سَيَّارَة",
    lemma_ar_bare: "سيارة",
    gloss_en: "car",
    pos: "noun",
    transliteration: "sayyāra",
    frequency_rank: 85,
    root: "س.ي.ر",
    root_meaning: "to walk / go",
    root_id: 20,
    score: 0.82,
    score_breakdown: { frequency: 0.35, root_familiarity: 0.3, recency_bonus: 0.0, known_siblings: 1, total_siblings: 4 },
  },
  {
    lemma_id: 51,
    lemma_ar: "مَكْتَبَة",
    lemma_ar_bare: "مكتبة",
    gloss_en: "library / bookstore",
    pos: "noun",
    transliteration: "maktaba",
    frequency_rank: 420,
    root: "ك.ت.ب",
    root_meaning: "writing / books",
    root_id: 1,
    score: 0.78,
    score_breakdown: { frequency: 0.22, root_familiarity: 0.4, recency_bonus: 0.0, known_siblings: 2, total_siblings: 5 },
  },
  {
    lemma_id: 52,
    lemma_ar: "جَمِيل",
    lemma_ar_bare: "جميل",
    gloss_en: "beautiful",
    pos: "adjective",
    transliteration: "jamīl",
    frequency_rank: 150,
    root: "ج.م.ل",
    root_meaning: "beauty",
    root_id: 21,
    score: 0.71,
    score_breakdown: { frequency: 0.30, root_familiarity: 0.0, recency_bonus: 0.0, known_siblings: 0, total_siblings: 3 },
  },
  {
    lemma_id: 53,
    lemma_ar: "مُسَافِر",
    lemma_ar_bare: "مسافر",
    gloss_en: "traveler",
    pos: "noun",
    transliteration: "musāfir",
    frequency_rank: 600,
    root: "س.ف.ر",
    root_meaning: "travel",
    root_id: 22,
    score: 0.65,
    score_breakdown: { frequency: 0.18, root_familiarity: 0.0, recency_bonus: 0.0, known_siblings: 0, total_siblings: 4 },
  },
  {
    lemma_id: 54,
    lemma_ar: "مُعَلِّم",
    lemma_ar_bare: "معلم",
    gloss_en: "teacher (m.)",
    pos: "noun",
    transliteration: "muʿallim",
    frequency_rank: 200,
    root: "ع.ل.م",
    root_meaning: "knowledge",
    root_id: 5,
    score: 0.75,
    score_breakdown: { frequency: 0.27, root_familiarity: 0.35, recency_bonus: 0.0, known_siblings: 1, total_siblings: 6 },
  },
];

export const MOCK_ANALYTICS: Analytics = {
  stats: {
    total_words: 302,
    known: 45,
    learning: 87,
    new: 170,
    due_today: 10,
    reviews_today: 0,
  },
  pace: {
    words_per_day_7d: 3.1,
    words_per_day_30d: 1.5,
    reviews_per_day_7d: 18.4,
    reviews_per_day_30d: 12.2,
    total_study_days: 14,
    current_streak: 3,
    longest_streak: 7,
  },
  cefr: {
    level: "Pre-A1",
    sublevel: "Pre-A1",
    known_words: 45,
    next_level: "A1",
    words_to_next: 255,
    reading_coverage_pct: 4.5,
  },
  daily_history: [
    { date: "2026-02-02", reviews: 15, words_learned: 2, cumulative_known: 35, accuracy: 78.5 },
    { date: "2026-02-03", reviews: 22, words_learned: 3, cumulative_known: 38, accuracy: 82.1 },
    { date: "2026-02-04", reviews: 18, words_learned: 1, cumulative_known: 39, accuracy: 75.0 },
    { date: "2026-02-06", reviews: 25, words_learned: 4, cumulative_known: 43, accuracy: 88.0 },
    { date: "2026-02-07", reviews: 12, words_learned: 1, cumulative_known: 44, accuracy: 91.7 },
    { date: "2026-02-08", reviews: 8, words_learned: 1, cumulative_known: 45, accuracy: 85.0 },
  ],
};
