import { Word, WordDetail, Stats, Analytics, LearnCandidate } from "./types";

const MOCK_WORDS_BASE: Array<
  Omit<Word, "times_seen" | "times_correct" | "last_reviewed" | "knowledge_score">
> = [
  { id: 1, arabic: "كِتَاب", english: "book", transliteration: "kitāb", root: "ك.ت.ب", pos: "noun", state: "known", due_date: null, frequency_rank: 142, cefr_level: "A1" },
  { id: 2, arabic: "مَدْرَسَة", english: "school", transliteration: "madrasa", root: "د.ر.س", pos: "noun", state: "learning", due_date: "2026-02-08", frequency_rank: 850, cefr_level: "A2" },
  { id: 3, arabic: "كَتَبَ", english: "he wrote", transliteration: "kataba", root: "ك.ت.ب", pos: "verb", state: "known", due_date: null, frequency_rank: 95, cefr_level: "A1" },
  { id: 4, arabic: "بَيْت", english: "house", transliteration: "bayt", root: "ب.ي.ت", pos: "noun", state: "learning", due_date: "2026-02-09", frequency_rank: 210, cefr_level: "A1" },
  { id: 5, arabic: "ذَهَبَ", english: "he went", transliteration: "dhahaba", root: "ذ.ه.ب", pos: "verb", state: "new", due_date: null, frequency_rank: 180, cefr_level: "A1" },
  { id: 6, arabic: "مَاء", english: "water", transliteration: "māʾ", root: "م.و.ه", pos: "noun", state: "known", due_date: null, frequency_rank: 320, cefr_level: "A1" },
  { id: 7, arabic: "قَرَأَ", english: "he read", transliteration: "qaraʾa", root: "ق.ر.أ", pos: "verb", state: "learning", due_date: "2026-02-08", frequency_rank: 480, cefr_level: "A1" },
  { id: 8, arabic: "مَدِينَة", english: "city", transliteration: "madīna", root: "م.د.ن", pos: "noun", state: "new", due_date: null, frequency_rank: 540, cefr_level: "A2" },
  { id: 9, arabic: "طَعَام", english: "food", transliteration: "ṭaʿām", root: "ط.ع.م", pos: "noun", state: "learning", due_date: "2026-02-10", frequency_rank: 1200, cefr_level: "A2" },
  { id: 10, arabic: "عَلِمَ", english: "he knew / learned", transliteration: "ʿalima", root: "ع.ل.م", pos: "verb", state: "new", due_date: null, frequency_rank: 75, cefr_level: "A1" },
  { id: 11, arabic: "وَلَد", english: "boy", transliteration: "walad", root: "و.ل.د", pos: "noun", state: "known", due_date: null, frequency_rank: 420, cefr_level: "A1" },
  { id: 12, arabic: "بِنْت", english: "girl", transliteration: "bint", root: "ب.ن.ت", pos: "noun", state: "known", due_date: null, frequency_rank: 610, cefr_level: "A2" },
  { id: 13, arabic: "أَكَلَ", english: "he ate", transliteration: "akala", root: "أ.ك.ل", pos: "verb", state: "learning", due_date: "2026-02-08", frequency_rank: 750, cefr_level: "A2" },
  { id: 14, arabic: "شَرِبَ", english: "he drank", transliteration: "shariba", root: "ش.ر.ب", pos: "verb", state: "new", due_date: null, frequency_rank: 890, cefr_level: "A2" },
  { id: 15, arabic: "كَبِير", english: "big", transliteration: "kabīr", root: "ك.ب.ر", pos: "adjective", state: "known", due_date: null, frequency_rank: 310, cefr_level: "A1" },
];

export const MOCK_WORDS: Word[] = MOCK_WORDS_BASE.map((w) => ({
  ...w,
  times_seen: w.state === "known" ? 12 : w.state === "learning" ? 6 : 0,
  times_correct: w.state === "known" ? 10 : w.state === "learning" ? 4 : 0,
  last_reviewed: w.state === "new" ? null : "2026-02-08T12:00:00Z",
  knowledge_score: w.state === "known" ? 84 : w.state === "learning" ? 48 : 0,
}));

export const MOCK_WORD_DETAIL: WordDetail = {
  id: 1,
  arabic: "كِتَاب",
  english: "book",
  transliteration: "kitāb",
  root: "ك.ت.ب",
  pos: "noun",
  state: "known",
  due_date: null,
  times_seen: 12,
  times_correct: 10,
  last_reviewed: "2026-02-08T12:00:00Z",
  knowledge_score: 86,
  frequency_rank: 142,
  cefr_level: "A1",
  times_reviewed: 12,
  correct_count: 10,
  forms_json: { plural: "كُتُب" },
  grammar_features: [
    { feature_key: "singular", category: "number", label_en: "Singular", label_ar: "مُفْرَد" },
  ],
  root_family: [
    { id: 3, arabic: "كَتَبَ", english: "he wrote" },
    { id: 16, arabic: "مَكْتَب", english: "office / desk" },
    { id: 17, arabic: "مَكْتَبَة", english: "library / bookstore" },
    { id: 18, arabic: "كَاتِب", english: "writer" },
  ],
  review_history: [],
  sentence_stats: [],
};

export const MOCK_STATS: Stats = {
  total_words: 302,
  known_words: 45,
  learning_words: 87,
  new_words: 170,
  due_today: 10,
  fsrs_due: 6,
  acquisition_due: 4,
  reviews_today: 0,
  streak_days: 3,
  total_reviews: 1260,
  lapsed: 4,
  acquiring: 0,
  encountered: 0,
};

export const MOCK_LEARN_CANDIDATES: LearnCandidate[] = [
  {
    lemma_id: 50,
    lemma_ar: "سَيَّارَة",
    lemma_ar_bare: "سيارة",
    gloss_en: "car",
    pos: "noun",
    transliteration: "sayyāra",
    frequency_rank: 85,
    cefr_level: "A2",
    root: "س.ي.ر",
    root_meaning: "to walk / go",
    root_id: 20,
    forms_json: { gender: "f", plural: "سَيَّارَات" },
    audio_url: null,
    example_ar: null,
    example_en: null,
    score: 0.82,
    score_breakdown: { frequency: 0.35, root_familiarity: 0.3, recency_bonus: 0.0, story_bonus: 0.0, encountered_bonus: 0.0, known_siblings: 1, total_siblings: 4 },
  },
  {
    lemma_id: 51,
    lemma_ar: "مَكْتَبَة",
    lemma_ar_bare: "مكتبة",
    gloss_en: "library / bookstore",
    pos: "noun",
    transliteration: "maktaba",
    frequency_rank: 420,
    cefr_level: "A1",
    root: "ك.ت.ب",
    root_meaning: "writing / books",
    root_id: 1,
    forms_json: { gender: "f", plural: "مَكْتَبَات" },
    audio_url: null,
    example_ar: null,
    example_en: null,
    score: 0.78,
    score_breakdown: { frequency: 0.22, root_familiarity: 0.4, recency_bonus: 0.0, story_bonus: 0.0, encountered_bonus: 0.0, known_siblings: 2, total_siblings: 5 },
  },
  {
    lemma_id: 52,
    lemma_ar: "جَمِيل",
    lemma_ar_bare: "جميل",
    gloss_en: "beautiful",
    pos: "adjective",
    transliteration: "jamīl",
    frequency_rank: 150,
    cefr_level: "A2",
    root: "ج.م.ل",
    root_meaning: "beauty",
    root_id: 21,
    forms_json: { feminine: "جَمِيلَة" },
    audio_url: null,
    example_ar: null,
    example_en: null,
    score: 0.71,
    score_breakdown: { frequency: 0.30, root_familiarity: 0.0, recency_bonus: 0.0, story_bonus: 0.0, encountered_bonus: 0.0, known_siblings: 0, total_siblings: 3 },
  },
  {
    lemma_id: 53,
    lemma_ar: "مُسَافِر",
    lemma_ar_bare: "مسافر",
    gloss_en: "traveler",
    pos: "noun",
    transliteration: "musāfir",
    frequency_rank: 600,
    cefr_level: "A2",
    root: "س.ف.ر",
    root_meaning: "travel",
    root_id: 22,
    forms_json: { gender: "m" },
    audio_url: null,
    example_ar: null,
    example_en: null,
    score: 0.65,
    score_breakdown: { frequency: 0.18, root_familiarity: 0.0, recency_bonus: 0.0, story_bonus: 0.0, encountered_bonus: 0.0, known_siblings: 0, total_siblings: 4 },
  },
  {
    lemma_id: 54,
    lemma_ar: "مُعَلِّم",
    lemma_ar_bare: "معلم",
    gloss_en: "teacher (m.)",
    pos: "noun",
    transliteration: "muʿallim",
    frequency_rank: 200,
    cefr_level: "A1",
    root: "ع.ل.م",
    root_meaning: "knowledge",
    root_id: 5,
    forms_json: { gender: "m" },
    audio_url: null,
    example_ar: null,
    example_en: null,
    score: 0.75,
    score_breakdown: { frequency: 0.27, root_familiarity: 0.35, recency_bonus: 0.0, story_bonus: 0.0, encountered_bonus: 0.0, known_siblings: 1, total_siblings: 6 },
  },
];

export const MOCK_ANALYTICS: Analytics = {
  stats: {
    total_words: 302,
    known: 45,
    learning: 87,
    new: 170,
    due_today: 10,
    fsrs_due: 6,
    acquisition_due: 4,
    reviews_today: 0,
    total_reviews: 1260,
    lapsed: 4,
    acquiring: 0,
    encountered: 0,
  },
  pace: {
    words_per_day_7d: 3.1,
    words_per_day_30d: 1.5,
    reviews_per_day_7d: 18.4,
    reviews_per_day_30d: 12.2,
    total_study_days: 14,
    current_streak: 3,
    longest_streak: 7,
    accuracy_7d: 83.4,
    study_days_7d: 5,
  },
  cefr: {
    level: "Pre-A1",
    sublevel: "Pre-A1",
    known_words: 45,
    acquiring_known: 12,
    next_level: "A1",
    words_to_next: 255,
    reading_coverage_pct: 4.5,
  },
  daily_history: [
    { date: "2026-02-02", reviews: 15, words_learned: 2, cumulative_known: 35, accuracy: 78.5 },
    { date: "2026-02-03", reviews: 22, words_learned: 3, cumulative_known: 38, accuracy: 82.1 },
    { date: "2026-02-04", reviews: 18, words_learned: 1, cumulative_known: 39, accuracy: 75.0 },
    { date: "2026-02-06", reviews: 25, words_learned: 4, cumulative_known: 43, accuracy: 88.0 },
    { date: "2026-02-07", reviews: 12, words_learned: 1, cumulative_known: 44, accuracy: 91.7 },
    { date: "2026-02-08", reviews: 8, words_learned: 1, cumulative_known: 45, accuracy: 85.0 },
  ],
};
