export const TOPIC_LABELS: Record<string, string> = {
  school: "School & Education",
  food: "Food & Cooking",
  family: "Family & Relationships",
  work: "Work & Career",
  travel: "Travel & Transport",
  home: "Home & Living",
  nature: "Nature & Environment",
  body: "Body & Health",
  time: "Time & Calendar",
  religion: "Religion & Spirituality",
  commerce: "Commerce & Money",
  media: "Media & Entertainment",
  politics: "Politics & Society",
  emotions: "Emotions & Feelings",
  social: "Social & Communication",
  daily_routine: "Daily Routine",
  language: "Language & Writing",
  science: "Science & Technology",
  military: "Military & Security",
  law: "Law & Justice",
};
